language: go
go:
  - 1.17

env:
  - "PATH=/home/travis/gopath/bin:$PATH"

services:
  - docker

before_install:
  - go get -d golang.org/x/tools/cmd/cover
  - go get -d github.com/mattn/goveralls

script:
  - go get -d github.com/golang/mock/mockgen@latest
  - go install -v github.com/golang/mock/mockgen && export PATH=$GOPATH/bin:$PATH;
  - go generate ./...
  - make test_travis
  - make build_travis
