---
benchmark_type: lxd
categories:
  -
    name: Logging and Auditing
    sub_category:
      name: 4.1 Configure Logging
      audit_tests:
        -
          name: '4.1.1.1 Ensure rsyslog is installed (Automated)'
          description: The rsyslog software is a recommended replacement to the original syslogd daemon which provide improvements over syslogd,
                        such as connection-oriented (i.e. TCP) transmission of logs, the option to log to database formats,
                        and the encryption of log data en route to a central logging server.
          profile_applicability: Level 1
          audit:
            - 'dpkg -s rsyslog 2> /dev/null |grep Status |awk -F ":" ''{print $2}'' |awk ''FNR <= 1'''
          remediation: 'nstall rsyslog:
                        # apt install rsyslog'
          check_type: multi_param
          eval_expr: "'$0' == 'install ok installed';"
        -
          name: '4.1.1.2 Ensure rsyslog Service is enabled (Automated)'
          description: Once the rsyslog package is installed it needs to be activated.
          profile_applicability: Level 1
          audit:
            - 'systemctl is-enabled rsyslog 2> /dev/null'
          remediation: 'Run the following commands to enable rsyslog:
                        # systemctl --now enable rsyslog'
          check_type: multi_param
          eval_expr: "'$0' == 'enabled';"
          additional_info: 'Additional methods of enabling a service exist. Consult your distribution documentation for appropriate methods.'
        -
          name: '4.1.1.3 Ensure logging is configured (Manual)'
          description: The /etc/rsyslog.conf and /etc/rsyslog.d/*.conf files specifies rules for logging and which files are to be used to log certain classes of messages.
          profile_applicability: Level 1
          audit:
            - 'ls -l /var/log/'
          remediation: 'Edit the following lines in the /etc/rsyslog.conf and /etc/rsyslog.d/*.conf files as appropriate for your environment:
                        *.emerg
                        auth,authpriv.*
                        mail.*
                        mail.info
                        mail.warning
                        mail.err
                        news.crit
                        news.err
                        news.notice
                        :omusrmsg:*
                         /var/log/auth.log
                        -/var/log/mail
                        -/var/log/mail.info
                        -/var/log/mail.warn
                         /var/log/mail.err
                        -/var/log/news/news.crit
                        -/var/log/news/news.err
                        -/var/log/news/news.notice
                        *.=warning;*.=err
                        *.crit
                        *.*;mail.none;news.none
                        local0,local1.*
                        local2,local3.*
                        local4,local5.*
                        local6,local7.*
                        -/var/log/warn
                         /var/log/warn
                        -/var/log/messages
                        -/var/log/localmessages
                        -/var/log/localmessages
                        -/var/log/localmessages
                        -/var/log/localmessages
                        Run the following command to reload the rsyslog configuration:
                        # systemctl reload rsyslog'
          check_type: multi_param
          references:
            - See the rsyslog.conf(5) man page for more information.
          additional_info: 'On some systems /var/log/secure should be used for authentication data rather than /var/log/auth.log.
                            Please consult your distribution-specific recommendations for further details.'
          type: manual

