---
benchmark_type: lxd
categories:
  -
    name: Access, Authentication and Authorization
    sub_category:
      name: 5.2 SSH Server Configuration
      audit_tests:
        -
          name: '5.2.1 Ensure permissions on /etc/ssh/sshd_config are configured (Automated)'
          description: The /etc/ssh/sshd_config file contains configuration specifications for sshd. The command below sets the owner and group of the file to root.
          audit:
            - 'stat /etc/ssh/sshd_config 2> /dev/null |grep Access |awk -F "Access:" ''{print $2}'' |awk ''FNR <= 1'''
          remedeation: 'Run the following commands to set ownership and permissions on /etc/ssh/sshd_config:
                         # chown root:root /etc/ssh/sshd_config
                         # chmod og-rwx /etc/ssh/sshd_config'
          check_type: multi_param
          additional_info: 'Additional methods of enabling a service exist. Consult your distribution documentation for appropriate methods.'
          eval_expr: "'$0' == '(0600/-rw-------)  Uid: (    0/    root)   Gid: (    0/    root)';"
        -
          name: '5.2.2 Ensure permissions on SSH private host key files are configured (Automated)'
          description: An SSH private key is one of two files used in SSH public key authentication.
                      In this authentication method, The possession of the private key is proof of identity.
                      Only a private key that corresponds to a public key will be able to authenticate successfully.
                      The private keys need to be stored and handled carefully, and no copies of the private key should be distributed.
          audit:
            - 'find /etc/ssh -xdev -type f -name ''ssh_host_*_key'' -exec stat {} \; | grep "Access: (" |awk -F "Access:" ''{print $2}'''
          remedeation: 'Run the following commands to set ownership and permissions on the private SSH host key files:
                        # find /etc/ssh -xdev -type f -name ''ssh_host_*_key'' -exec chown root:root {} \;
                        # find /etc/ssh -xdev -type f -name ''ssh_host_*_key'' -exec chmod 0600 {} \;'
          check_type: multi_param
          eval_expr: "'$0' == '(0600/-rw-------)  Uid: (    0/    root)   Gid: (    0/    root)';"
        -
          name: '5.2.3 Ensure permissions on SSH public host key files are configured (Automated)'
          description: An SSH public key is one of two files used in SSH public key authentication.
                      In this authentication method, a public key is a key that can be used for verifying digital
                      signatures generated using a corresponding private key. Only a public key that corresponds to a private
                      key will be able to authenticate successfully.
          audit:
            - 'find /etc/ssh -xdev -type f -name ''ssh_host_*_key.pub'' -exec stat {} \; | grep "Access: (" |awk -F "Access:" ''{print $2}'''
          remedeation: 'Run the following commands to set permissions and ownership on the SSH host public key files:
                        # find /etc/ssh -xdev -type f -name ''ssh_host_*_key.pub'' -exec chmod go-wx {} \;
                        # find /etc/ssh -xdev -type f -name ''ssh_host_*_key.pub'' -exec chown root:root {} \;'
          check_type: multi_param
          eval_expr: "'$0' == '(0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)';"
        -
          name: '5.2.4 Ensure SSH Protocol is not set to 1 (Automated)'
          description: Older versions of SSH support two different and incompatible protocols
                        SSH1 and SSH2. SSH1 was the original protocol and was subject to security issues.
                        SSH2 is more advanced and secure.
          audit:
            - 'sshd -T 2> /dev/null | grep -Ei ''^\s*protocol\s+(1|1\s*,\s*2|2\s*,\s*1)\s*'''
          remedeation: 'Edit the /etc/ssh/sshd_config file to set the parameter as follows: Protocol 2'
          check_type: multi_param
          eval_expr: "'$0' == '';"
          additional_info: 'This command not longer exists in newer versions of SSH.
                            This check is still being included for systems that may be running an older version of SSH. As of
                            openSSH version 7.4 this parameter will not cause an issue when included.'

