---
benchmark_type: lxd
categories:
  -
    name: System Maintenance
    sub_category:
      name: 6.2 User and Group Settings
      audit_tests:
        -
          name: '6.2.1 Ensure password fields are not empty (Automated)'
          description: 'An account with an empty password field means that anybody may log in as that user without providing a password.'
          audit:
            - 'awk -F: ''($2 == "" ) { print $1 " does not have a password "}'' /etc/shadow 2> /dev/null'
          remedeation: 'If any accounts in the /etc/shadow file do not have a password, run the following command to lock the account until it can be determined why it does not have a password:
                        # passwd -l <username>
                        Also, check to see if the account is logged in and investigate what it is being used for to determine if it needs to be forced off.'
          check_type: multi_param
          eval_expr: "'$0' == '';"
        -
          name: '6.2.2 Ensure no legacy "+" entries exist in /etc/passwd (Automated)'
          description: 'The character + in various files used to be markers for systems to insert data from NIS maps at
                        a certain point in a system configuration file. These entries are no longer required on most
                        systems, but may exist in files that have been imported from other platforms.'
          audit:
            - 'grep ''^\+:'' /etc/passwd 2> /dev/null'
          remedeation: 'Remove any legacy entries from /etc/passwd if they exist.'
          check_type: multi_param
          eval_expr: "'$0' == '';"
        -
          name: '6.2.3 Ensure all users'' home directories exist (Automated)'
          description: 'The character + in various files used to be markers for systems to insert data
                        from NIS maps at a certain point in a system configuration file. These entries are no longer
                        required on most systems, but may exist in files that have been imported from other platforms.'
          audit:
            - '#!/bin/bash grep -E -v ''^(halt|sync|shutdown)'' /etc/passwd | awk -F: ''($7 != "''"$(which nologin)"''" && $7 != "/bin/false") { print $1 " " $6 }'' | while read -r user dir; do
                                                                          if [ ! -d "$dir" ]; then
                                                                          echo "The home directory ($dir) of user $user does not exist."
                                                                          fi done'
          remedeation: 'If any users home directories do not exist, create them and make sure the respective user owns the directory.
                        Users without an assigned home directory should be removed or assigned a home directory as appropriate.'
          additional_info: 'The audit script checks all users with interactive shells except halt, sync, shutdown, and nfsnobody.'
          check_type: multi_param
          eval_expr: "'$0' == '';"
        -
          name: '6.2.4 Ensure no legacy "+" entries exist in /etc/shadow (Automated)'
          description: 'The character + in various files used to be markers for systems to insert data from NIS maps at a certain point in a system configuration file.
                        These entries are no longer required on most systems, but may exist in files that have been imported from other platforms.'
          audit:
            - 'grep ''^\+:'' /etc/shadow 2> /dev/null'
          remedeation: 'Remove any legacy entries from /etc/shadow if they exist.'
          check_type: multi_param
          eval_expr: "'$0' == '';"
